### ISSUE TITLE
Runtime Error while installing

### ISSUE THREAD

**Issue by hanssssssss** [FuxiCV/pt_mesh_renderer#4]
Hi , I installed your work in other device(win10 gtx2090 vs2019 python3.7 torch 1.6.0 cuda 10.1) and I ecounteered some problems. Do you have any idea about it?

Thanks.

```
FAILED: C:/Users/Administrator/Desktop/新文件夹/pt_mesh_renderer-master/pt_mesh_renderer-master/build/temp.win-amd64-3.7/Release/pt_mesh_renderer/kernels/rasterize_triangles_cuda_impl.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\ProgramData\Anaconda3\envs\face\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\envs\face\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\envs\face\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\envs\face\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\ProgramData\Anaconda3\envs\face\include -IC:\ProgramData\Anaconda3\envs\face\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\include" -c C:\Users\Administrator\Desktop\新文件夹\pt_mesh_renderer-master\pt_mesh_renderer-master\pt_mesh_renderer\kernels\rasterize_triangles_cuda_impl.cu -o C:\Users\Administrator\Desktop\新文件夹\pt_mesh_renderer-master\pt_mesh_renderer-master\build\temp.win-amd64-3.7\Release\pt_mesh_renderer/kernels/rasterize_triangles_cuda_impl.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=rasterize_triangles_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
C:/ProgramData/Anaconda3/envs/face/lib/site-packages/torch/include\c10/util/ThreadLocalDebugInfo.h(12): warning: modifier is ignored on an enum specifier

C:/ProgramData/Anaconda3/envs/face/lib/site-packages/torch/include\ATen/record_function.h(18): warning: modifier is ignored on an enum specifier

C:/ProgramData/Anaconda3/envs/face/lib/site-packages/torch/include\torch/csrc/autograd/profiler.h(97): warning: modifier is ignored on an enum specifier

C:/ProgramData/Anaconda3/envs/face/lib/site-packages/torch/include\torch/csrc/autograd/profiler.h(126): warning: modifier is ignored on an enum specifier

C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/include\cmath(137): error: calling a __host__ function("__floorf") from a __global__ function("pytorch_mesh_renderer::RasterizeTrianglesForwardCudaKernel<float> ") is not allowed

C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/include\cmath(137): error: identifier "__floorf" is undefined in device code

C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/include\cmath(133): error: calling a __host__ function("__ceilf") from a __global__ function("pytorch_mesh_renderer::RasterizeTrianglesForwardCudaKernel<float> ") is not allowed

C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/include\cmath(133): error: identifier "__ceilf" is undefined in device code

C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/include\cmath(137): error: calling a __host__ function("__floorf") from a __global__ function("pytorch_mesh_renderer::RasterizeTrianglesForwardCudaKernel<float> ") is not allowed

C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/include\cmath(137): error: identifier "__floorf" is undefined in device code

C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/include\cmath(133): error: calling a __host__ function("__ceilf") from a __global__ function("pytorch_mesh_renderer::RasterizeTrianglesForwardCudaKernel<float> ") is not allowed

C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/include\cmath(133): error: identifier "__ceilf" is undefined in device code

8 errors detected in the compilation of "C:/Users/ADMINI~1/AppData/Local/Temp/tmpxft_00002d40_00000000-10_rasterize_triangles_cuda_impl.cpp1.ii".
rasterize_triangles_cuda_impl.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\face\lib\site-packages\torch\utils\cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "C:\ProgramData\Anaconda3\envs\face\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    cmdclass={'build_ext': BuildExtension}
  File "C:\ProgramData\Anaconda3\envs\face\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Anaconda3\envs\face\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\envs\face\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\envs\face\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\face\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\ProgramData\Anaconda3\envs\face\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install    self.run_command('bdist_egg')
  File "C:\ProgramData\Anaconda3\envs\face\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\envs\face\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\face\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\ProgramData\Anaconda3\envs\face\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command    self.run_command(cmdname)
  File "C:\ProgramData\Anaconda3\envs\face\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\envs\face\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\face\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\ProgramData\Anaconda3\envs\face\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\ProgramData\Anaconda3\envs\face\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\envs\face\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\face\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\ProgramData\Anaconda3\envs\face\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\ProgramData\Anaconda3\envs\face\lib\site-packages\torch\utils\cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "C:\ProgramData\Anaconda3\envs\face\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\ProgramData\Anaconda3\envs\face\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\ProgramData\Anaconda3\envs\face\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\ProgramData\Anaconda3\envs\face\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\ProgramData\Anaconda3\envs\face\lib\site-packages\torch\utils\cpp_extension.py", line 631, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\ProgramData\Anaconda3\envs\face\lib\site-packages\torch\utils\cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\ProgramData\Anaconda3\envs\face\lib\site-packages\torch\utils\cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
```

**Comment by davystrong** [comment]
Might be related, haven't verified, but this issue has appeared in various places this week: https://trac.ffmpeg.org/ticket/9150

**Comment by MariaWang96** [comment]
Maybe this help. [https://blog.csdn.net/baobei0112/article/details/114521271](url)

**Comment by hanssssssss** [comment]
> Might be related, haven't verified, but this issue has appeared in various places this week: https://trac.ffmpeg.org/ticket/9150

Thanks for your help. I think I fix this problem.
